# render.yaml - Disagreement.AI Infrastructure Blueprint (Final)
services:
  # Service: The Node.js/Express Backend API
  - name: disagreement-ai-api
    type: web
    runtime: node
    rootDir: ./server
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: AI_MEDIATOR_USER_ID
        fromSecret: ai_mediator_user_id