# render.yaml - Disagreement.AI Infrastructure Blueprint (v2)
services:
  # Service: The FastAPI Backend API
  - name: disagreement-ai-api
    type: web
    runtime: python
    # This should be the path to your server code from the project root
    rootDir: ./server
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      # Note: We will add all other environment variables,
      # including the Database URL and other secrets,
      # directly in the Render dashboard for security.