version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # This is the timezone for your n8n instance to ensure schedules run correctly.
      - GENERIC_TIMEZONE=America/New_York

      # You can add the environment variables from your main .env file here
      # so your n8n workflows can access them. For example:
      # - EMAIL_API_KEY=${EMAIL_API_KEY}
      # - BACKEND_API_KEY=${BACKEND_API_KEY}

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    driver: local